---
- name: Provision WSL
  hosts: localhost
  connection: local
  become: true
  vars:
    username_on_the_host: lortega
  tasks:
    - name: Include vars.yml
      ansible.builtin.include_vars: vars.yml

    - name: Update and upgrade all packages
      ansible.builtin.apt:
        upgrade: 'yes'
        update_cache: 'yes'

    - name: Include python
      ansible.builtin.include_tasks: tasks/python.yml

    - name: Include bat
      ansible.builtin.include_tasks: tasks/bat.yml

    - name: Include CA
      ansible.builtin.include_tasks: tasks/ca.yml

    - name: Include dos2unix
      ansible.builtin.include_tasks: tasks/dos2unix.yml

    - name: Include git
      ansible.builtin.include_tasks: tasks/git.yml

    - name: Include go
      ansible.builtin.include_tasks: tasks/go.yml

    - name: Include rust
      ansible.builtin.include_tasks: tasks/rust.yml

    - name: Include keychain
      ansible.builtin.include_tasks: tasks/keychain.yml

    - name: Include kubectl
      ansible.builtin.include_tasks: tasks/kubectl.yml

    - name: Include gpg
      ansible.builtin.include_tasks: tasks/gpg.yml

    - name: Include motd
      ansible.builtin.include_tasks: tasks/motd.yml

    - name: Include nmap
      ansible.builtin.include_tasks: tasks/nmap.yml

    - name: Include ntp
      ansible.builtin.include_tasks: tasks/ntp.yml

    - name: Include packer-builder-arm
      ansible.builtin.include_tasks: tasks/packer-builder-arm.yml

    - name: Include packer
      ansible.builtin.include_tasks: tasks/packer.yml

    - name: Include restic
      ansible.builtin.include_tasks: tasks/restic.yml

    - name: Include snmp
      ansible.builtin.include_tasks: tasks/snmp.yml

    - name: Include ssh_config
      ansible.builtin.include_tasks: tasks/ssh_config.yml

    - name: Include sshpass
      ansible.builtin.include_tasks: tasks/sshpass.yml

    - name: Include sudoers
      ansible.builtin.include_tasks: tasks/sudoers.yml

    - name: Include terraform
      ansible.builtin.include_tasks: tasks/terraform.yml

    - name: Include terragrunt
      ansible.builtin.include_tasks: tasks/terragrunt.yml

    - name: Include unzip
      ansible.builtin.include_tasks: tasks/unzip.yml

    - name: Include whois
      ansible.builtin.include_tasks: tasks/whois.yml

    - name: Include zsh
      ansible.builtin.include_tasks: tasks/zsh.yml
