---
- name: Add nodesource Apt signing key
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    dest: /etc/apt/keyrings/nodesource.asc
    mode: "0644"

- name: Add nodesource Apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
    state: present
    filename: nodesource

- name: Install nodejs
  ansible.builtin.apt:
    name: nodejs
    state: present
