---
- name: Add Hashicorp Apt signing key
  ansible.builtin.apt_key:
    url: "https://apt.releases.hashicorp.com/gpg"
    state: present
  retries: 3
  delay: 3

- name: Add Hashicorp Apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release|lower }} main"
    state: present
    filename: hashicorp

- name: Install Terraform
  ansible.builtin.apt:
    name: terraform
    state: present