---
- name: Add Hashicorp Apt signing key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp.asc
    mode: "0644"

- name: Add Hashicorp Apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: hashicorp

- name: Install vault
  ansible.builtin.apt:
    name: "vault"
    state: present

- name: Create config directory
  ansible.builtin.file:
    path: "/home/{{ username_on_the_host }}/.vault"
    state: directory
    owner: "{{ username_on_the_host }}"
    group: "{{ username_on_the_host }}"
    mode: "0700"

- name: Copy certs files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ username_on_the_host }}/.vault/certs/{{ item }}"
    mode: "0644"
  with_fileglob: ./files/vault/certs/*
